open Parser

test pconc "conc [atmp, 1.0]"
test pload "ld [a, atmp]"
test padd "add [a, atmp, b]"
test psub "sub [a, atmp, b]"
test pmul "mul [a, atmp, b]"
test pdiv "div [a, atmp, b]"
test psqrt "sqrt [a, atmp]"
test pcmp "cmp [a, b]"
test pcommands "ld [a, atmp], add [a, atmp, b], sub [a, atmp, b]"
test pstep "step [ld [a, atmp], add [a, atmp, b], sub [a, atmp, b]]"
test proot "conc [atmp, 1.0]"
test proots "conc [atmp, 1.0], step [ld [a, atmp], add [a, atmp, b], sub [a, atmp, b]]"
test pcrn "crn = {conc [atmp, 1.0], step [ld [a, atmp], add [a, atmp, b], sub [a, atmp, b]]}"
